### ISSUE TITLE
添加对socks代理的支持

### ISSUE THREAD

**Issue by jiangzc** [poemdistance/google-translate#2]
安装PySocks  `pip3 install PySocks` 就可以用socks代理了

https://github.com/poemdistance/google-translate/blob/1afc622c6df3a9b7b0acd19dd3eabe395ad24cd8/tests/packageTest.py#L3-L5

` proxy = { 'https':'socks5://127.0.0.1:2334' } `

**Comment by poemdistance** [comment]
已添加
